language: python

python:
  - 3.6

env:
  global:
    # Doctr deploy key for drdoctr/testing-travis-ci-both (.org)
    - secure: "rQ3fD/HmzqbXJS0WFvdGo7cqQyyiDA1+QCJq06QVc6eTPIJ0NlqPJAMSiKFqp9UgJw9lg1BrT5aEOEPpVdxrqRSZmLWWXrvNs0MB0CRVTeuCjUXWb8i4VLv32TSmc+EPcSgI5Q6H3+CmLkFG79w7toe/BCVNU4CpYKpf5MTIKZgHofAy9ev8HJFyeGQgiJGEWzY1TEXnQTOT39aY/r7gJQj13O1ccUgPExtLjUDeDo+ADMgViDpcbIXWQpWNwecSLdM7+PN803pvs5hvbsPJUUXkx+E7k4h1+kdYm9D/yNXz/CFFFwuXr7RPTCChRsfkxG5CO8LgVOFtcrEiiw5V8v0cm5jDbFkWTR/epPKEonWfBn6WIr7hxyyANx1GAoj6zLn56tt5aePfJ6dxMv6zigbwoSNat+LbUbbHpB7QAuqEsgeint/eW8SUCpihqttEbxnrVybSGe/DE27p6tVAwu2E+xPpWOal8N3QcxsQtDVFgQxvc63w2MfrM0rbuzt9s9/lxMjs+YR9aFaW59OZKEYn+w8AJDzfFLnAEN0/qt2IlKICfj7d/al1emY1haeNwVc4W9xRLEjWKprrL+5uxF/96DGd78BGQ+V0c2ZKscTuCGlhPPhrsMVBJVJo3NTZuaXVF5/qbys8CginSIqXT1ITktKiYtQ/kDZMXcNsqqg="
    # Doctr deploy key for drdoctr/testing-travis-ci-both (.com)
    - secure: "azEsylsy1Avy+awHH1FiN+gawNPmPhdkPDXRc+acojJuMxjVwG8YrbzETQH5Dy+uxKyCz9ETLRj+4/DFXQRiNZA3/dZKJT9pCKiAaXPPvqmaJPKtc7sh+J4/4CTHZs4eOEzAGalyWG4NVwZZh+WDrDgtTejXPRN44ayBXt86zrOvRNrTgEejOgkUD7FfR/WXmNXBVJE5rCil0f/0NEoiFdGkllcbWHapfksQdnxbXKwJpXGB1TvJIbH7JGQHrzvSv9a9Qwmi5Rx5/HGAOS0mcViNQtft/fYf/d4RgENPcMXyIi774Wr5K8pkyCg3aMfZ0x2/omov1qlTLCMLheyweQi6V0QmE7uoJxt6JCoMRAEKB5gjH44r8Gcz9jEQ04cdpVBKc7VdkAXaA0lpeDV+tzaoxQ1N14aqNcf7ap/HF43AS8AIumdDk5I+osQYxpMGqLTyyx6S0gcveFCjOY9NO6ZCcOlPmGdqCtixZOIaP5DdYcR8UFfucXJcFa/+AH641Bc73X/Wpl62R4Qy/CXkO2BN1c3jzDbuiBr6sLoSiO0mBozKcfA/k/C7luIf8/dmmAAOR/PzBKS1iM2Cb/6YnvqLX1FKAPPQV9i43LHrfQLDdVLKl3J4JBbtcxo+5mESpHTd9LhaxuhNCkFUqLSAoPMgVxWKtTwaamoqevTDlcU="

script:
  - set -e
  - date > test
  - date > test-token
  - pip install git+https://github.com/drdoctr/doctr.git@dotcom-fixes
  - |
    if [[ $TRAVIS_BUILD_WEB_URL == *"travis-ci.com"* ]]; then
        doctr deploy --built-docs test . --key-path github_deploy_key_drdoctr_testing_travis_ci_both-com.enc;
    else
        doctr deploy --built-docs test . --key-path github_deploy_key_drdoctr_testing_travis_ci_both-org.enc;
    fi
