language: python

python:
  - 3.6

env:
  global:
    # Doctr deploy key for drdoctr/testing-travis-ci-both
    - secure: "rQ3fD/HmzqbXJS0WFvdGo7cqQyyiDA1+QCJq06QVc6eTPIJ0NlqPJAMSiKFqp9UgJw9lg1BrT5aEOEPpVdxrqRSZmLWWXrvNs0MB0CRVTeuCjUXWb8i4VLv32TSmc+EPcSgI5Q6H3+CmLkFG79w7toe/BCVNU4CpYKpf5MTIKZgHofAy9ev8HJFyeGQgiJGEWzY1TEXnQTOT39aY/r7gJQj13O1ccUgPExtLjUDeDo+ADMgViDpcbIXWQpWNwecSLdM7+PN803pvs5hvbsPJUUXkx+E7k4h1+kdYm9D/yNXz/CFFFwuXr7RPTCChRsfkxG5CO8LgVOFtcrEiiw5V8v0cm5jDbFkWTR/epPKEonWfBn6WIr7hxyyANx1GAoj6zLn56tt5aePfJ6dxMv6zigbwoSNat+LbUbbHpB7QAuqEsgeint/eW8SUCpihqttEbxnrVybSGe/DE27p6tVAwu2E+xPpWOal8N3QcxsQtDVFgQxvc63w2MfrM0rbuzt9s9/lxMjs+YR9aFaW59OZKEYn+w8AJDzfFLnAEN0/qt2IlKICfj7d/al1emY1haeNwVc4W9xRLEjWKprrL+5uxF/96DGd78BGQ+V0c2ZKscTuCGlhPPhrsMVBJVJo3NTZuaXVF5/qbys8CginSIqXT1ITktKiYtQ/kDZMXcNsqqg="

script:
  - set -e
  - date > test
  - date > test-token
  - pip install git+https://github.com/drdoctr/doctr.git@dotcom-fixes
  - doctr deploy --built-docs test .
